USE [empresa]
GO


IF OBJECT_ID(N'dbo.ACCOUNT', N'U') IS  NULL
BEGIN

	CREATE TABLE [dbo].[ACCOUNT](
		[ACCOUNTNO] [int] IDENTITY(1,1) NOT NULL,
		[EMPNO] [int] NOT NULL,
		[AMOUNT] [money] NOT NULL,
	 CONSTRAINT [PK_ACCOUNT] PRIMARY KEY CLUSTERED 
	(
		[ACCOUNTNO] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	

	ALTER TABLE [dbo].[ACCOUNT]  WITH CHECK ADD  CONSTRAINT [FK_ACCOUNT_EMP] FOREIGN KEY([EMPNO])
	REFERENCES [dbo].[EMP] ([EMPNO])
	

	ALTER TABLE [dbo].[ACCOUNT] CHECK CONSTRAINT [FK_ACCOUNT_EMP]
	

END



IF OBJECT_ID(N'dbo.ACC_MOVEMENT', N'U') IS  NULL
BEGIN
CREATE TABLE [dbo].[ACC_MOVEMENT](
	[ACCOUNT_MOV_ID] [int] IDENTITY(1,1) NOT NULL,
	[ACCOUNT_ORIGIN_ID] [int] NOT NULL,
	[ACCOUNT_DEST_ID] [int] NOT NULL,
	[AMOUNT] [money] NOT NULL,
	[DATETIME] [datetime] NOT NULL,
 CONSTRAINT [PK_ACC_MOVEMENT] PRIMARY KEY CLUSTERED 
(
	[ACCOUNT_MOV_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE [dbo].[ACC_MOVEMENT]  WITH CHECK ADD  CONSTRAINT [FK_ACC_MOVEMENT_ACCOUNT] FOREIGN KEY([ACCOUNT_DEST_ID])
REFERENCES [dbo].[ACCOUNT] ([ACCOUNTNO])


ALTER TABLE [dbo].[ACC_MOVEMENT] CHECK CONSTRAINT [FK_ACC_MOVEMENT_ACCOUNT]

END
